title: " "
theme: jekyll-theme-architect
email: acetcom@gmail.com
google_analytics: G-X32W9DH490
description: >- # this means to ignore newlines until "baseurl:"
 Open Source implementation for 5G Core and EPC, i.e. the core network of LTE/NR network (Release-17)
