title: Open5GS
theme: jekyll-theme-architect
email: acetcom@gmail.com
google_analytics: UA-139225646-1
description: >- # this means to ignore newlines until "baseurl:"
 Open source project of 5GC and EPC (Release-16)
